function j = JacobianPinholeLinescanXYZ(in1,in2)
%JACOBIANPINHOLELINESCANXYZ
%    J = JACOBIANPINHOLELINESCANXYZ(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    13-Jun-2021 00:46:27

X = in2(:,1);
Y = in2(:,2);
Z = in2(:,3);
fy = in1(:,7);
rx = in1(:,6);
ry = in1(:,5);
rz = in1(:,4);
t1 = in1(:,1);
t2 = in1(:,2);
t3 = in1(:,3);
t5 = cos(rx);
t6 = cos(ry);
t7 = cos(rz);
t8 = sin(rx);
t9 = sin(ry);
t10 = sin(rz);
t11 = X.*t9;
t12 = Z.*t5.*t6;
t13 = Y.*t6.*t8;
t14 = -t11;
t15 = t3+t12+t13+t14;
t16 = 1.0./t15.^2;
j = reshape([t16.*(t1.*t9+Y.*t7.*t8+Z.*t5.*t7+t3.*t6.*t7-Y.*t5.*t9.*t10+Z.*t8.*t9.*t10),fy.*t16.*(t2.*t9+Y.*t8.*t10+Z.*t5.*t10+t3.*t6.*t10+Y.*t5.*t7.*t9-Z.*t7.*t8.*t9),-t16.*(X.*t7.*t8+Z.*t6.*t10+t1.*t6.*t8+t3.*t5.*t10+t5.*t10.*t14-t3.*t7.*t8.*t9),-fy.*t16.*(X.*t8.*t10-Z.*t6.*t7-t3.*t5.*t7+t2.*t6.*t8+t5.*t7.*t11-t3.*t8.*t9.*t10),-t16.*(X.*t5.*t7-Y.*t6.*t10+t1.*t5.*t6-t3.*t8.*t10+t8.*t10.*t11-t3.*t5.*t7.*t9),-fy.*t16.*(X.*t5.*t10+Y.*t6.*t7+t2.*t5.*t6+t3.*t7.*t8+t7.*t8.*t14-t3.*t5.*t9.*t10)],[2,3]);
