function j = JacobianPinholeCameraLineScan(in1,in2,v)
%JACOBIANPINHOLECAMERALINESCAN
%    [J1,J2] = JACOBIANPINHOLECAMERALINESCAN(IN1,IN2,V)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    13-Jun-2021 00:50:40

K1 = in1(:,9);
K2 = in1(:,10);
P1 = in1(:,11);
X = in2(:,1);
Y = in2(:,2);
Z = in2(:,3);
fy = in1(:,7);
rx = in1(:,6);
ry = in1(:,5);
rz = in1(:,4);
t1 = in1(:,1);
t2 = in1(:,2);
t3 = in1(:,3);
v0 = in1(:,8);
t5 = cos(rx);
t6 = cos(ry);
t7 = cos(rz);
t8 = sin(rx);
t9 = sin(ry);
t10 = sin(rz);
t13 = -v0;
t11 = X.*t6;
t12 = X.*t9;
t14 = t5.*t7;
t15 = t5.*t10;
t16 = t7.*t8;
t17 = t8.*t10;
t19 = Y.*t5.*t6;
t20 = Z.*t5.*t6;
t22 = Y.*t6.*t8;
t23 = Z.*t5.*t9;
t24 = Z.*t6.*t8;
t25 = Y.*t8.*t9;
t27 = t13+v;
t18 = t7.*t11;
t21 = t10.*t11;
t26 = -t12;
t28 = t9.*t15;
t29 = t9.*t16;
t30 = t9.*t17;
t31 = t9.*t14;
t32 = t27.^2;
t33 = -t24;
t45 = t11+t23+t25;
t34 = -t28;
t35 = -t29;
t36 = t14+t30;
t37 = t17+t31;
t40 = t19+t33;
t48 = t3+t20+t22+t26;
t38 = Y.*t36;
t39 = Z.*t37;
t41 = t15+t35;
t42 = t16+t34;
t49 = 1.0./t48;
t43 = Y.*t41;
t44 = Z.*t42;
t50 = t49.^2;
t46 = -t43;
t47 = -t44;
t51 = t1+t18+t39+t46;

onesVec = ones(size(X));


j1 = [t49,0.0.*onesVec,-t50.*t51,-t49.*(t21+t38+t47),t49.*(t7.*t26+Y.*t6.*t16+Z.*t6.*t14)+t45.*t50.*t51,t49.*(Y.*t37+Z.*t41)-t40.*t50.*t51,0.0.*onesVec,0.0.*onesVec,0.0.*onesVec,0.0.*onesVec,0.0.*onesVec];
t52 = t2+t21+t38+t47;
j2 = [0.0.*onesVec,fy.*t49,-fy.*t50.*t52,fy.*t49.*(t18+t39+t46),fy.*t49.*(t10.*t26+Y.*t6.*t17+Z.*t6.*t15)+fy.*t45.*t50.*t52,-fy.*t49.*(Y.*t42+Z.*t36)-fy.*t40.*t50.*t52,t49.*t52,K1.*t32.*-3.0-K2.*t32.^2.*5.0-P1.*(v.*2.0-v0.*2.0)+1.0.*onesVec,t27.^3,t27.^5,t32];

j = [j1;j2];

end
