function [f,j] = LinescanPinholeOptQuat(in1,in2,v)
%LINESCANPINHOLEOPTQUAT
%    [F,J1,J2] = LINESCANPINHOLEOPTQUAT(IN1,IN2,V)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Jun-2021 20:03:49

K1 = in1(:,10);
K2 = in1(:,11);
P1 = in1(:,12);
X = in2(:,1);
Y = in2(:,2);
Z = in2(:,3);
fy = in1(:,8);
rw = in1(:,4);
rx = in1(:,5);
ry = in1(:,6);
rz = in1(:,7);
t1 = in1(:,1);
t2 = in1(:,2);
t3 = in1(:,3);
v0 = in1(:,9);
t5 = rw.^2;
t6 = rx.^2;
t7 = ry.^2;
t8 = rz.^2;
t9 = X.*rw.*2.0;
t10 = X.*rx.*2.0;
t11 = X.*ry.*2.0;
t12 = X.*rz.*2.0;
t13 = Y.*rw.*2.0;
t14 = Y.*rx.*2.0;
t15 = Y.*ry.*2.0;
t16 = Y.*rz.*2.0;
t17 = Z.*rw.*2.0;
t18 = Z.*rx.*2.0;
t19 = Z.*ry.*2.0;
t20 = Z.*rz.*2.0;
t21 = -v0;
t69 = X.*rw.*ry.*-2.0;
t70 = Y.*rw.*rz.*-2.0;
t76 = Z.*fy.*rw.*rx.*-2.0;
t22 = -t11;
t23 = -t16;
t24 = -t18;
t25 = X.*t5;
t26 = X.*t6;
t27 = X.*t7;
t28 = X.*t8;
t29 = Z.*t5;
t30 = Z.*t6;
t31 = Z.*t7;
t32 = Z.*t8;
t33 = ry.*t9;
t34 = rz.*t10;
t35 = rx.*t13;
t36 = rz.*t13;
t37 = ry.*t14;
t38 = rz.*t15;
t39 = ry.*t17;
t40 = rz.*t18;
t41 = t1.*t5;
t42 = t3.*t5;
t43 = t1.*t6;
t44 = t3.*t6;
t45 = t1.*t7;
t46 = t3.*t7;
t47 = t1.*t8;
t48 = t3.*t8;
t53 = fy.*rz.*t9;
t54 = fy.*ry.*t10;
t55 = fy.*rx.*t17;
t56 = fy.*rz.*t19;
t57 = fy.*t2.*t5;
t58 = fy.*t2.*t6;
t59 = fy.*t2.*t7;
t60 = fy.*t2.*t8;
t71 = t21+v;
t72 = Y.*fy.*t5;
t73 = Y.*fy.*t6;
t74 = Y.*fy.*t7;
t75 = Y.*fy.*t8;
t77 = t69.*v0;
t89 = t5+t6+t7+t8;
t49 = t29.*v0;
t50 = t30.*v0;
t51 = t31.*v0;
t52 = t32.*v0;
t61 = t33.*v0;
t62 = t34.*v0;
t63 = t35.*v0;
t64 = t38.*v0;
t65 = t42.*v0;
t66 = t44.*v0;
t67 = t46.*v0;
t68 = t48.*v0;
t78 = -t27;
t79 = -t28;
t80 = -t30;
t81 = -t31;
t82 = t21.*t30;
t83 = t21.*t31;
t84 = t71.^2;
t85 = t71.^3;
t86 = t71.^5;
t87 = -t73;
t88 = -t75;
t90 = 1.0./t89;
t91 = t90.^2;
t92 = t25+t26+t37+t39+t40+t41+t43+t45+t47+t70+t78+t79;
t93 = t29+t32+t34+t35+t38+t42+t44+t46+t48+t69+t80+t81;
t96 = t49+t52+t53+t54+t56+t57+t58+t59+t60+t62+t63+t64+t65+t66+t67+t68+t72+t74+t76+t77+t82+t83+t87+t88;
t94 = 1.0./t93;

onesVec = ones(size(X));

factor = 1000;

f = [factor.*t90.*t92;v-K1.*t85-K2.*t86-P1.*t84-t94.*t96];


j1 = factor.*[1.0.*onesVec,0.0.*onesVec,0.0.*onesVec,t90.*(t9+t19+t23+rw.*t1.*2.0)-rw.*t91.*t92.*2.0.*onesVec,t90.*(t10+t15+t20+rx.*t1.*2.0)-rx.*t91.*t92.*2.0.*onesVec,t90.*(t14+t17+t22+ry.*t1.*2.0)-ry.*t91.*t92.*2.0.*onesVec,-t90.*(t12+t13+t24-rz.*t1.*2.0)-rz.*t91.*t92.*2.0.*onesVec,0.0.*onesVec,0.0.*onesVec,0.0.*onesVec,0.0.*onesVec,0.0.*onesVec];


t95 = t94.^2;
j2 = [0.0.*onesVec,-t94.*(fy.*t5+fy.*t6+fy.*t7+fy.*t8),-t94.*(t5.*v0+t6.*v0+t7.*v0+t8.*v0)+t89.*t95.*t96,-t94.*(fy.*t12+fy.*t13+t14.*v0+t17.*v0-Z.*fy.*rx.*2.0-X.*ry.*v0.*2.0+fy.*rw.*t2.*2.0+rw.*t3.*v0.*2.0)+t95.*t96.*(t14+t17+t22+rw.*t3.*2.0),-t94.*(fy.*t11+t12.*v0+t13.*v0-Y.*fy.*rx.*2.0-Z.*fy.*rw.*2.0-Z.*rx.*v0.*2.0+fy.*rx.*t2.*2.0+rx.*t3.*v0.*2.0)+t95.*t96.*(t12+t13+t24+rx.*t3.*2.0),-t94.*(fy.*t10+fy.*t15+fy.*t20+t16.*v0-X.*rw.*v0.*2.0-Z.*ry.*v0.*2.0+fy.*ry.*t2.*2.0+ry.*t3.*v0.*2.0)-t95.*t96.*(t9+t19+t23-ry.*t3.*2.0),-t94.*(fy.*t9+fy.*t19+t10.*v0+t15.*v0+t20.*v0-Y.*fy.*rz.*2.0+fy.*rz.*t2.*2.0+rz.*t3.*v0.*2.0)+t95.*t96.*(t10+t15+t20+rz.*t3.*2.0),-t94.*(Y.*t5-Y.*t6+Y.*t7-Y.*t8+ry.*t10+rz.*t9+rz.*t19+t2.*t5+t2.*t6+t2.*t7+t2.*t8-Z.*rw.*rx.*2.0),K1.*t84.*3.0+K2.*t84.^2.*5.0+P1.*(v.*2.0-v0.*2.0)-1.0.*onesVec,-t85,-t86,-t84];

j = [j1;j2];

end
