function [f,j] = LinescanPinholeOptQuat(in1,in2,v)
%LINESCANPINHOLEOPTQUAT
%    [F,J1,J2] = LINESCANPINHOLEOPTQUAT(IN1,IN2,V)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    02-Jun-2021 16:50:39

K1 = in1(:,10);
K2 = in1(:,11);
P1 = in1(:,12);
X = in2(:,1);
Y = in2(:,2);
Z = in2(:,3);
fy = in1(:,8);
rw = in1(:,4);
rx = in1(:,5);
ry = in1(:,6);
rz = in1(:,7);
t1 = in1(:,1);
t2 = in1(:,2);
t3 = in1(:,3);
v0 = in1(:,9);
t5 = rw.^2;
t6 = rx.^2;
t7 = ry.^2;
t8 = rz.^2;
t9 = X.*rw.*2.0;
t10 = X.*rx.*2.0;
t11 = X.*ry.*2.0;
t12 = X.*rz.*2.0;
t13 = Y.*rw.*2.0;
t14 = Y.*rx.*2.0;
t15 = Y.*ry.*2.0;
t16 = Y.*rz.*2.0;
t17 = Z.*rw.*2.0;
t18 = Z.*rx.*2.0;
t19 = Z.*ry.*2.0;
t20 = Z.*rz.*2.0;
t21 = rw.*t3.*2.0;
t22 = rx.*t3.*2.0;
t23 = ry.*t3.*2.0;
t24 = rz.*t3.*2.0;
t25 = -v0;
t74 = X.*rw.*ry.*-2.0;
t75 = Y.*rw.*rz.*-2.0;
t81 = Z.*fy.*rw.*rx.*-2.0;
t26 = -t11;
t27 = -t16;
t28 = -t18;
t29 = -t23;
t30 = X.*t5;
t31 = X.*t6;
t32 = X.*t7;
t33 = X.*t8;
t34 = Z.*t5;
t35 = Z.*t6;
t36 = Z.*t7;
t37 = Z.*t8;
% t38 = ry.*t9;
t39 = rz.*t10;
t40 = rx.*t13;
% t41 = rz.*t13;
t42 = ry.*t14;
t43 = rz.*t15;
t44 = ry.*t17;
t45 = rz.*t18;
t46 = t1.*t5;
t47 = t3.*t5;
t48 = t1.*t6;
t49 = t3.*t6;
t50 = t1.*t7;
t51 = t3.*t7;
t52 = t1.*t8;
t53 = t3.*t8;
t58 = fy.*rz.*t9;
t59 = fy.*ry.*t10;
% t60 = fy.*rx.*t17;
t61 = fy.*rz.*t19;
t62 = fy.*t2.*t5;
t63 = fy.*t2.*t6;
t64 = fy.*t2.*t7;
t65 = fy.*t2.*t8;
t76 = t25+v;
t77 = Y.*fy.*t5;
t78 = Y.*fy.*t6;
t79 = Y.*fy.*t7;
t80 = Y.*fy.*t8;
t82 = t74.*v0;
t94 = t5+t6+t7+t8;
t95 = t10+t15+t20+t24;
t54 = t34.*v0;
% t55 = t35.*v0;
% t56 = t36.*v0;
t57 = t37.*v0;
% t66 = t38.*v0;
t67 = t39.*v0;
t68 = t40.*v0;
t69 = t43.*v0;
t70 = t47.*v0;
t71 = t49.*v0;
t72 = t51.*v0;
t73 = t53.*v0;
t83 = -t32;
t84 = -t33;
t85 = -t35;
t86 = -t36;
t87 = t25.*t35;
t88 = t25.*t36;
t89 = t76.^2;
t90 = t76.^3;
t91 = t76.^5;
t92 = -t78;
t93 = -t80;
t96 = t14+t17+t21+t26;
t97 = t12+t13+t22+t28;
t98 = t9+t19+t27+t29;
t99 = t30+t31+t42+t44+t45+t46+t48+t50+t52+t75+t83+t84;
t100 = t34+t37+t39+t40+t43+t47+t49+t51+t53+t74+t85+t86;
t103 = t54+t57+t58+t59+t61+t62+t63+t64+t65+t67+t68+t69+t70+t71+t72+t73+t77+t79+t81+t82+t87+t88+t92+t93;
t101 = 1.0./t100;

% f1 = abs(t99.*t101);
% f2 = abs(v-K1.*t90-K2.*t91-P1.*t89-t101.*t103);

factor = 100;
f = [factor.*t99.*t101;v-K1.*t90-K2.*t91-P1.*t89-t101.*t103];


onesVec = ones(size(X));


t102 = t101.^2;
j1 = factor.*[t94.*t101,0.0.*onesVec,-t94.*t99.*t102,t101.*(t9+t19+t27+rw.*t1.*2.0)-t96.*t99.*t102,t101.*(t10+t15+t20+rx.*t1.*2.0)-t97.*t99.*t102,t101.*(t14+t17+t26+ry.*t1.*2.0)+t98.*t99.*t102,-t101.*(t12+t13+t28-rz.*t1.*2.0)-t95.*t99.*t102,0.0.*onesVec,0.0.*onesVec,0.0.*onesVec,0.0.*onesVec,0.0.*onesVec];

j2 = [0.0.*onesVec,-t101.*(fy.*t5+fy.*t6+fy.*t7+fy.*t8),-t101.*(t5.*v0+t6.*v0+t7.*v0+t8.*v0)+t94.*t102.*t103,-t101.*(fy.*t12+fy.*t13+t14.*v0+t17.*v0+t21.*v0-Z.*fy.*rx.*2.0-X.*ry.*v0.*2.0+fy.*rw.*t2.*2.0)+t96.*t102.*t103,-t101.*(fy.*t11+t12.*v0+t13.*v0+t22.*v0-Y.*fy.*rx.*2.0-Z.*fy.*rw.*2.0-Z.*rx.*v0.*2.0+fy.*rx.*t2.*2.0)+t97.*t102.*t103,-t101.*(fy.*t10+fy.*t15+fy.*t20+t16.*v0+t23.*v0-X.*rw.*v0.*2.0-Z.*ry.*v0.*2.0+fy.*ry.*t2.*2.0)-t98.*t102.*t103,-t101.*(fy.*t9+fy.*t19+t10.*v0+t15.*v0+t20.*v0+t24.*v0-Y.*fy.*rz.*2.0+fy.*rz.*t2.*2.0)+t95.*t102.*t103,-t101.*(Y.*t5-Y.*t6+Y.*t7-Y.*t8+ry.*t10+rz.*t9+rz.*t19+t2.*t5+t2.*t6+t2.*t7+t2.*t8-Z.*rw.*rx.*2.0),K1.*t89.*3.0+K2.*t89.^2.*5.0+P1.*(v.*2.0-v0.*2.0)-1.0.*onesVec,-t90,-t91,-t89];


j = [j1;j2];

end
