function j = JacobianLinescanPinholeOptReprojection(in1,in2)
%JacobianLinescanPinholeOptReprojection
%    [J1,J2] = JacobianLinescanPinholeOptReprojection(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    14-Jan-2023 17:12:25

K1 = in1(:,9);
K2 = in1(:,10);
T1 = in1(:,11);
X = in2(:,1);
Y = in2(:,2);
Z = in2(:,3);
fy = in1(:,7);
rx = in1(:,6);
ry = in1(:,5);
rz = in1(:,4);
t1 = in1(:,1);
t2 = in1(:,2);
t3 = in1(:,3);
t5 = cos(rx);
t6 = cos(ry);
t7 = cos(rz);
t8 = sin(rx);
t9 = sin(ry);
t10 = sin(rz);
t11 = t2.*2.0;
t12 = X.*t6;
t13 = X.*t9;
t14 = t5.*t7;
t15 = t5.*t10;
t16 = t7.*t8;
t17 = t8.*t10;
t19 = Y.*t5.*t6;
t20 = Z.*t5.*t6;
t22 = Y.*t6.*t8;
t23 = Z.*t5.*t9;
t24 = Z.*t6.*t8;
t26 = Y.*t8.*t9;
t18 = t7.*t12;
t21 = t10.*t12;
t25 = t10.*t13;
t27 = -t13;
t28 = t9.*t15;
t29 = t9.*t16;
t30 = t9.*t17;
t32 = t9.*t14;
t33 = Z.*t6.*t15;
t34 = Y.*t6.*t17;
t35 = -t24;
t51 = t12+t23+t26;
t31 = t21.*2.0;
t36 = -t25;
t37 = -t28;
t38 = -t29;
t39 = t14+t30;
t40 = t17+t32;
t44 = t19+t35;
t56 = t3+t20+t22+t27;
t41 = Y.*t39;
t42 = Z.*t39;
t43 = Z.*t40;
t45 = t15+t38;
t46 = t16+t37;
t57 = 1.0./t56;
t62 = t33+t34+t36;
t47 = t41.*2.0;
t48 = Y.*t45;
t49 = Y.*t46;
t50 = Z.*t46;
t58 = t57.^2;
t59 = t57.^3;
t61 = t57.^5;
t52 = t50.*2.0;
t53 = -t48;
t54 = -t50;
t60 = t58.^2;
t63 = t42+t49;
t55 = -t52;
t64 = t18+t43+t53;
t66 = t2+t21+t41+t54;
t65 = t1+t64;

onesVec = ones(size(X));

j1 = [fy.*t57,0.0.*onesVec,-fy.*t58.*t65,-fy.*t57.*(t21+t41+t54),fy.*t57.*(t7.*t27+Y.*t6.*t16+Z.*t6.*t14)+fy.*t51.*t58.*t65,fy.*t57.*(Y.*t40+Z.*t45)-fy.*t44.*t58.*t65,t57.*t65,0.0.*onesVec,0.0.*onesVec,0.0.*onesVec,0.0.*onesVec];
t67 = t66.^2;
t68 = t66.^3;
t70 = t11+t31+t47+t55;
t69 = t67.^2;
t71 = K1.*t58.*t67;
t72 = K2.*t60.*t69;
t73 = t71+t72+1.0;
mt1 = [0.0.*onesVec,-fy.*(t57.*t73+T1.*t58.*t70.*3.0+t57.*t66.*(K1.*t58.*t70+K2.*t60.*t68.*4.0)),fy.*(T1.*t59.*t67.*6.0+t58.*t66.*t73+t57.*t66.*(K1.*t59.*t67.*2.0+K2.*t61.*t69.*4.0)),-fy.*(t57.*t66.*(K1.*t58.*t64.*t66.*2.0+K2.*t60.*t64.*t68.*4.0)+t57.*t64.*t73+T1.*t58.*t64.*t66.*6.0),-fy.*(t57.*t62.*t73+t57.*t66.*(K1.*t51.*t59.*t67.*2.0+K2.*t51.*t61.*t69.*4.0+K1.*t58.*t62.*t66.*2.0+K2.*t60.*t62.*t68.*4.0)+T1.*t51.*t59.*t67.*6.0+T1.*t58.*t62.*t66.*6.0+t51.*t58.*t66.*t73),fy.*(t57.*t63.*t73+t57.*t66.*(K1.*t44.*t59.*t67.*2.0+K2.*t44.*t61.*t69.*4.0+K1.*t58.*t63.*t66.*2.0+K2.*t60.*t63.*t68.*4.0)+T1.*t44.*t59.*t67.*6.0+T1.*t58.*t63.*t66.*6.0+t44.*t58.*t66.*t73)];
mt2 = [T1.*t58.*t67.*-3.0-t57.*t66.*t73,-1.0.*onesVec,-fy.*t59.*t68,-fy.*t61.*t66.^5,fy.*t58.*t67.*-3.0];
j2 = [mt1,mt2];

j = [j1;j2];

end
