function j = JacobianCrossRatio_D(in1,in2)
%JACOBIANCROSSRATIO_D
%    J = JACOBIANCROSSRATIO_D(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2020 01:16:16

A = in2(:,1);
B = in2(:,2);
C = in2(:,3);
a = in1(:,1);
b = in1(:,2);
c = in1(:,3);
d = in1(:,4);
t2 = A.*a.*b;
t3 = A.*a.*c;
t4 = B.*a.*b;
t5 = A.*b.*d;
t6 = B.*a.*d;
t7 = B.*b.*c;
t8 = C.*a.*c;
t9 = A.*c.*d;
t10 = C.*a.*d;
t11 = C.*b.*c;
t12 = B.*c.*d;
t13 = C.*b.*d;
t14 = -B;
t15 = -C;
t16 = -b;
t17 = -c;
t18 = -d;
t19 = A+t14;
t20 = A+t15;
t21 = B+t15;
t22 = -t3;
t23 = -t4;
t24 = -t5;
t25 = -t10;
t26 = -t11;
t27 = -t12;
t28 = a+t16;
t29 = a+t17;
t30 = a+t18;
t31 = b+t17;
t32 = b+t18;
t33 = c+t18;
t34 = t2+t6+t7+t8+t9+t13+t22+t23+t24+t25+t26+t27;
t35 = 1.0./t34.^2;
j = [-t19.*t20.*t21.*t31.*t32.*t33.*t35,t19.*t20.*t21.*t29.*t30.*t33.*t35,-t19.*t20.*t21.*t28.*t30.*t32.*t35,t19.*t20.*t21.*t28.*t29.*t31.*t35];
