function j = JacobianTransPat2Frame(in1,in2)
%JACOBIANTRANSPAT2FRAME
%    J = JACOBIANTRANSPAT2FRAME(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    22-May-2020 15:09:46

X = in2(:,1);
Y = in2(:,2);
Z = in2(:,3);
rx = in1(:,6);
ry = in1(:,5);
rz = in1(:,4);
t2 = cos(rx);
t3 = cos(ry);
t4 = cos(rz);
t5 = sin(rx);
t6 = sin(ry);
t7 = sin(rz);
t8 = t2.*t4;
t9 = t2.*t7;
t10 = t4.*t5;
t11 = t5.*t7;
t12 = t6.*t9;
t13 = t6.*t10;
t14 = t6.*t11;
t15 = t6.*t8;
t16 = -t12;
t17 = -t13;
t18 = t8+t14;
t19 = t11+t15;
t20 = t9+t17;
t21 = t10+t16;
j = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-Y.*t18+Z.*t21-X.*t3.*t7,-Y.*t20+Z.*t19+X.*t3.*t4,0.0,-X.*t4.*t6+Y.*t3.*t10+Z.*t3.*t8,-X.*t6.*t7+Y.*t3.*t11+Z.*t3.*t9,-X.*t3-Y.*t5.*t6-Z.*t2.*t6,Y.*t19+Z.*t20,-Y.*t21-Z.*t18,Y.*t2.*t3-Z.*t3.*t5,t3.*t4,t3.*t7,-t6,-t9+t13,t18,t3.*t5,t19,-t10+t12,t2.*t3],[3,9]);
