function j = JacobianLinearEqY_Value(m,c,x)
%JACOBIANLINEAREQY_VALUE
%    J = JACOBIANLINEAREQY_VALUE(M,C,X)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    21-Oct-2020 11:57:21

j = [x,1.0];
