function j = JacobianCrossRatio_B(in1,in2)
%JACOBIANCROSSRATIO_B
%    J = JACOBIANCROSSRATIO_B(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2020 01:16:14

A = in2(:,1);
C = in2(:,2);
D = in2(:,3);
a = in1(:,1);
b = in1(:,2);
c = in1(:,3);
d = in1(:,4);
t2 = A.*a.*c;
t3 = A.*a.*d;
t4 = A.*b.*c;
t5 = C.*a.*b;
t6 = A.*b.*d;
t7 = C.*a.*c;
t8 = D.*a.*b;
t9 = C.*b.*d;
t10 = D.*a.*d;
t11 = D.*b.*c;
t12 = C.*c.*d;
t13 = D.*c.*d;
t14 = -C;
t15 = -D;
t16 = -b;
t17 = -c;
t18 = -d;
t19 = A+t14;
t20 = A+t15;
t21 = C+t15;
t22 = -t3;
t23 = -t4;
t24 = -t7;
t25 = -t8;
t26 = -t9;
t27 = -t13;
t28 = a+t16;
t29 = a+t17;
t30 = a+t18;
t31 = b+t17;
t32 = b+t18;
t33 = c+t18;
t34 = t2+t5+t6+t10+t11+t12+t22+t23+t24+t25+t26+t27;
t35 = 1.0./t34.^2;
j = [-t19.*t20.*t21.*t31.*t32.*t33.*t35,t19.*t20.*t21.*t29.*t30.*t33.*t35,-t19.*t20.*t21.*t28.*t30.*t32.*t35,t19.*t20.*t21.*t28.*t29.*t31.*t35];
