function j = JacobianLinescanPinholeOptReprojectionXYZ(in1,in2)
%JacobianLinescanPinholeOptReprojectionXYZ
%    J = JacobianLinescanPinholeOptReprojectionXYZ(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    14-Jan-2023 17:03:58

K1 = in1(:,9);
K2 = in1(:,10);
T1 = in1(:,11);
X = in2(:,1);
Y = in2(:,2);
Z = in2(:,3);
fy = in1(:,7);
rx = in1(:,6);
ry = in1(:,5);
rz = in1(:,4);
t1 = in1(:,1);
t2 = in1(:,2);
t3 = in1(:,3);
t5 = cos(rx);
t6 = cos(ry);
t7 = cos(rz);
t8 = sin(rx);
t9 = sin(ry);
t10 = sin(rz);
t11 = X.*t9;
t12 = t5.*t7;
t13 = t7.*t8;
t14 = Z.*t5.*t6;
t15 = X.*t6.*t10;
t16 = Y.*t6.*t8;
t18 = t5.*t9.*t10;
t19 = t8.*t9.*t10;
t17 = -t11;
t20 = -t18;
t21 = t12+t19;
t22 = Y.*t21;
t23 = t13+t20;
t26 = t3+t14+t16+t17;
t24 = Z.*t23;
t27 = 1.0./t26;
t25 = -t24;
t28 = t27.^2;
t29 = t27.^3;
t31 = t27.^5;
t30 = t28.^2;
t32 = t2+t15+t22+t25;
t33 = t32.^2;
t34 = t32.^3;
t35 = t33.^2;
t36 = K1.*t28.*t33;
t37 = K2.*t30.*t35;
t38 = t36+t37+1.0;
mt1 = [fy.*t28.*(Y.*t13+Y.*t20+Z.*t12+Z.*t19+t1.*t9+t3.*t6.*t7),-fy.*(t27.*t32.*(K1.*t9.*t29.*t33.*2.0+K2.*t9.*t31.*t35.*4.0+K1.*t6.*t10.*t28.*t32.*2.0+K2.*t6.*t10.*t30.*t34.*4.0)+T1.*t9.*t29.*t33.*6.0+t6.*t10.*t27.*t38+t9.*t28.*t32.*t38+T1.*t6.*t10.*t28.*t32.*6.0),-fy.*t28.*(X.*t13+Z.*t6.*t10+t1.*t6.*t8+t3.*t5.*t10-t3.*t9.*t13+t5.*t10.*t17),-fy.*(t27.*t32.*(K1.*t21.*t28.*t32.*2.0+K2.*t21.*t30.*t34.*4.0-K1.*t6.*t8.*t29.*t33.*2.0-K2.*t6.*t8.*t31.*t35.*4.0)+t21.*t27.*t38+T1.*t21.*t28.*t32.*6.0-T1.*t6.*t8.*t29.*t33.*6.0-t6.*t8.*t28.*t32.*t38)];
mt2 = [-fy.*t28.*(X.*t12-Y.*t6.*t10+t1.*t5.*t6-t3.*t8.*t10-t3.*t9.*t12+t8.*t10.*t11),fy.*(t27.*t32.*(K1.*t23.*t28.*t32.*2.0+K2.*t23.*t30.*t34.*4.0+K1.*t5.*t6.*t29.*t33.*2.0+K2.*t5.*t6.*t31.*t35.*4.0)+t23.*t27.*t38+T1.*t23.*t28.*t32.*6.0+T1.*t5.*t6.*t29.*t33.*6.0+t5.*t6.*t28.*t32.*t38)];
j = reshape([mt1,mt2],2,3);
