function j = JacobianCrossRatio_C(in1,in2)
%JACOBIANCROSSRATIO_C
%    J = JACOBIANCROSSRATIO_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Oct-2020 01:16:15

A = in2(:,1);
B = in2(:,2);
D = in2(:,3);
a = in1(:,1);
b = in1(:,2);
c = in1(:,3);
d = in1(:,4);
t2 = A.*a.*b;
t3 = B.*a.*b;
t4 = A.*a.*d;
t5 = A.*b.*c;
t6 = B.*a.*c;
t7 = A.*c.*d;
t8 = B.*b.*d;
t9 = D.*a.*c;
t10 = B.*c.*d;
t11 = D.*a.*d;
t12 = D.*b.*c;
t13 = D.*b.*d;
t14 = -B;
t15 = -D;
t16 = -b;
t17 = -c;
t18 = -d;
t19 = A+t14;
t20 = A+t15;
t21 = B+t15;
t22 = -t3;
t23 = -t4;
t24 = -t5;
t25 = -t9;
t26 = -t10;
t27 = -t13;
t28 = a+t16;
t29 = a+t17;
t30 = a+t18;
t31 = b+t17;
t32 = b+t18;
t33 = c+t18;
t34 = t2+t6+t7+t8+t11+t12+t22+t23+t24+t25+t26+t27;
t35 = 1.0./t34.^2;
j = [t19.*t20.*t21.*t31.*t32.*t33.*t35,-t19.*t20.*t21.*t29.*t30.*t33.*t35,t19.*t20.*t21.*t28.*t30.*t32.*t35,-t19.*t20.*t21.*t28.*t29.*t31.*t35];
